[mainnet]
endpoint_url = "${MAINNET_RPC_URL}"
 
[mainnet.address]
compoundV3 = "0xc3d688B66703497DAA19211EEdff47f25384cdc3"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
usdc = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"

[sepolia]
endpoint_url = "${SEPOLIA_RPC_URL}"

[sepolia.address]
weth = "0x2D5ee574e710219a521449679A4A7f2B43f046ad"
comet = "0x2943ac1216979aD8dB76D9147F64E61adc126e96"
usdc = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
comp =  "0xc00e94Cb662C3520282E6f5717214004A7f26888"
comet_usdc = "0xc3d688B66703497DAA19211EEdff47f25384cdc3"
vault = "0xA4BCba5425A3b56169810C6eF9EF6d8d2A012a89"
