[mainnet]
endpoint_url = "${MAINNET_RPC_URL}"

[mainnet.address]
uniswap_v2_router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
compoundV3 = "0xc3d688B66703497DAA19211EEdff47f25384cdc3"
comet_rewards = "0x1B0e765F6224C21223AeA2af16c1C46E38885a40"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
usdc = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
comp = "0xc00e94Cb662C3520282E6f5717214004A7f26888"

[sepolia]
endpoint_url = "${SEPOLIA_RPC_URL}"

[sepolia.address]
uniswap_v2_router = "0xeE567Fe1712Faf6149d80dA1E6934E354124CfE3"
comet_usdc = "0xc3d688B66703497DAA19211EEdff47f25384cdc3"
comet_rewards = "0x8bF5b658bdF0388E8b482ED51B14aef58f90abfD"
usdc = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
comp = "0xc00e94Cb662C3520282E6f5717214004A7f26888"
weth = "0x2D5ee574e710219a521449679A4A7f2B43f046ad"
vault = "0x8425eBdc68f16c44195d9F8e14C4F54e3BacAB33"
