[mainnet]
endpoint_url = "${MAINNET_RPC_URL}"

[mainnet.address]
uniswap_v2_router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
compoundV3 = "0xc3d688B66703497DAA19211EEdff47f25384cdc3"
comet_rewards = "0x1B0e765F6224C21223AeA2af16c1C46E38885a40"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
usdc = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
comp = "0xc00e94Cb662C3520282E6f5717214004A7f26888"
#aave_v3_pool = "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2"
#aave_v3_usdc_aToken = "0x98C23E9d8f34FEFb1B7BD6a91B7FF122F4e16F5c"
#aave_v3_rewards_controller = "0x8164Cc65827dcFe994AB23944CBC90e0aa80bFcb"
#aave_reward_token = "0x4da27a545c0c5B758a6BA100e3a049001de870f5"

[sepolia]
endpoint_url = "${SEPOLIA_RPC_URL}"

[sepolia.address]
uniswap_v2_router = "0xeE567Fe1712Faf6149d80dA1E6934E354124CfE3"
comet_usdc = "0xc3d688B66703497DAA19211EEdff47f25384cdc3"
comet_rewards = "0x8bF5b658bdF0388E8b482ED51B14aef58f90abfD"
weth = "0x2D5ee574e710219a521449679A4A7f2B43f046ad"
usdc = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
comp = "0xc00e94Cb662C3520282E6f5717214004A7f26888"
#aave_v3_pool = "0x6Ae43d3271ff6888e7Fc43Fd7321a503ff738951"
#aave_v3_usdc_aToken = "0x16dA4541aD1807f4443d92D26044C1147406EB80"
#aave_v3_rewards_controller = "0xBA25de9a7DC623B30799F33B770d31B44c2C3b77"
#aave_reward_token = "0x387d311e47e80b498169e6fb51d3193167d89F7D"

#uniswap_v2_router = "0xC532a74256D3Db42D0Bf7a0400fEFDbad7694008"
